
env = Environment(CPPFLAGS='-Weffc++ -Wall -DUNIX -g -DDEBUG -m64')

#env.Program(target='BenchmarkGPU', source=['BenchmarkGPU.cpp', 'GPU.cpp', 'ArraySumUtil.cpp', 'Stopwatch.cpp'])

env.Program(target='FMATotal', source=['FMATotal.cpp','Stopwatch.cpp'])

env.Append(FRAMEWORKS = ['OpenCL'])


